### PR TITLE
Fix msvc and xcode generators

### PR DESCRIPTION
**Pull request by uilianries**
- Update some points to work with python3 on Windows and OSX

### CODE REVIEW

**Review by SSE4 — CHANGES_REQUESTED** [review]
I think it's better to make required changes into our fork https://github.com/bincrafters/gyp

**Comment by uilianries** [comment]
@SSE4 should we create a new tag ?

**Comment by SSE4** [comment]
@uilianries yes, it would be nice

**Comment by uilianries** [comment]
now we have two options,

remove all branches related to 20171101 and distribute only 20181120

or, add an error condition to 20171101 for msvc and osx

WDYT @SSE4 ?

**Comment by SSE4** [comment]
@uilianries just remove old, I don't think they are very frequently used

**Comment by uilianries** [comment]
@SSE4 this will require removing the package as well

**Comment by SSE4** [comment]
I don't think it's a problem
also, we need to create latest alias (like for msys2_installer)
AFAIK the only project using it is https://github.com/bincrafters/conan-libuv, which has to be updated

**Comment by uilianries** [comment]
@SSE4 nice, I'm gonna remove it

**Pull request closed without merging**
